### ISSUE TITLE
Beta issue: Does not update body stats and goals

### ISSUE THREAD

**Issue by iamjomz** [Jefit/iOS-Bug-Report#11]
![5](https://cloud.githubusercontent.com/assets/16845665/16303849/6a58989e-3985-11e6-9621-00f35575347d.png)
![6](https://cloud.githubusercontent.com/assets/16845665/16303850/6a5aefa4-3985-11e6-93ef-880f3c694933.png)

**Comment by davidpao** [comment]
Looks like this was fixed as well
