### ISSUE TITLE
Beta: Location is Missing

### ISSUE THREAD

**Issue by iamjomz** [Jefit/iOS-Bug-Report#13]
![8](https://cloud.githubusercontent.com/assets/16845665/16328489/58fca4b8-3a0d-11e6-8d5f-cdcc544d1161.PNG)
![9](https://cloud.githubusercontent.com/assets/16845665/16328490/5902fe4e-3a0d-11e6-8262-dd39284b8540.PNG)

**Comment by davidpao** [comment]
Seems fixed
