### ISSUE TITLE
Beta: Nude pictures

### ISSUE THREAD

**Issue by iamjomz** [Jefit/iOS-Bug-Report#17]
![14](https://cloud.githubusercontent.com/assets/16845665/16379641/4ff943a4-3ca5-11e6-9e40-938f74a52170.png)
![15](https://cloud.githubusercontent.com/assets/16845665/16379642/4ffdb614-3ca5-11e6-85b9-b556fb148d9a.png)

**Comment by yinglin83** [comment]
that's something serious. I wonder why all different people have the same nude pictures.
