### ISSUE TITLE
Beta: Elite training reports missing headers 14D - 3M - 6M

### ISSUE THREAD

**Issue by iamjomz** [Jefit/iOS-Bug-Report#24]
This is different for different people. I can see my headers 
![18](https://cloud.githubusercontent.com/assets/16845665/16435187/af2c8616-3dc6-11e6-904e-3538287770b8.png)

While for this user, the headers have gone missing. 
![20](https://cloud.githubusercontent.com/assets/16845665/16435214/de1267de-3dc6-11e6-9903-2e98f9949cf5.png)

**Comment by davidpao** [comment]
Fixed:

https://github.com/Jefit/JEFIT_iOS/pull/716
