### ISSUE TITLE
Beta: Unable to add duration

### ISSUE THREAD

**Issue by iamjomz** [Jefit/iOS-Bug-Report#26]
It seems that it is impossible to change the duration for a particular exercise in a workout.

See attached the example for exercise "plank". In my workout, it is not possible to change the duration to execute this exercise from 60 sec to (for example 90 sec). Swiping left on the exercise and selecting modify does only give the option to change the amount of sets, repetitions and rest time.
![27](https://cloud.githubusercontent.com/assets/16845665/16560588/f3cbdbe6-4226-11e6-8303-1659efc4537c.png)
![28](https://cloud.githubusercontent.com/assets/16845665/16560589/f44ab600-4226-11e6-9a41-f4a9c190100c.png)
![29](https://cloud.githubusercontent.com/assets/16845665/16560590/f50f73d2-4226-11e6-8c55-b65fe82cba0a.png)

**Comment by davidpao** [comment]
Well this works just like the Android version, so I am closing this

**Comment by davidpao** [comment]
Did fix a few minor issues with the pop-up for smaller views...
