### ISSUE TITLE
Beta: Ability to unfriend my own self 

### ISSUE THREAD

**Issue by iamjomz** [Jefit/iOS-Bug-Report#28]
My account -> "Me"-button

click on "explore"-button to see my work-out feed.

click on my picture.

option to unfriend myself 

![30](https://cloud.githubusercontent.com/assets/16845665/16560867/84c05086-4228-11e6-9da6-9f933471c3ec.png)

**Comment by davidpao** [comment]
Fixed, button will be hidden if you are clicking on your own now
