### ISSUE TITLE
Beta issue #1

### ISSUE THREAD

**Issue by iamjomz** [Jefit/iOS-Bug-Report#7]
- It always selects my target reps as preloaded reps, even if I change the setting to 'last log'. Force close and opening the app again, the setting is changed back to 'target reps' even though I saved it as 'last log'; 
- When I finish a exercise it would be nice to see what my last log was for the next exercise so you can prep for this, currently it displays a summary of the exercise I have just completed; 
- I'm not able to download the exercise images, it download the full 50mb, says it's installing, but then nothing happens.

**Comment by davidpao** [comment]
Issue 2 is a suggestion, pulling that one out...

**Comment by davidpao** [comment]
Issue 1 and 3 done... 
- incorrect variable updated
- zip file had issues

**Comment by davidpao** [comment]
https://github.com/Jefit/JEFIT_iOS/pull/701
