### ISSUE TITLE
Beta Issue: Elite training reports: headers "14D", "30D", "3M"... not visible. - I think I found it. Disregard this. 

### ISSUE THREAD

**Issue by iamjomz** [Jefit/iOS-Bug-Report#8]
https://jefit.zendesk.com/agent/tickets/14614

![elitetraining](https://cloud.githubusercontent.com/assets/16845665/16302963/8b8c20b2-3980-11e6-80dd-11c54e59d8f4.PNG)

**Comment by davidpao** [comment]
Disregarded...
