### ISSUE TITLE
Beta issue: The same exercise can be found on workout days. See screenshot

### ISSUE THREAD

**Issue by iamjomz** [Jefit/iOS-Bug-Report#9]
![1](https://cloud.githubusercontent.com/assets/16845665/16303345/bcde12cc-3982-11e6-994b-0b5bed0d56bc.png)
![2](https://cloud.githubusercontent.com/assets/16845665/16303352/c130c130-3982-11e6-9f96-602e0d8332c2.png)
![3](https://cloud.githubusercontent.com/assets/16845665/16303395/01786f7c-3983-11e6-80b3-8371bbb3bd6f.png)

**Comment by davidpao** [comment]
https://github.com/Jefit/JEFIT_iOS/pull/698

Fixed it was reusing the header for some reason... fixed so this should not be an issue anymore
